### PR TITLE
Code reloading. Fixes #212

### LINKED ISSUE #212: Code Reloading
Allow code to be modified while at break-point, then continue executing the modified code.

### PR DESCRIPTION
**Pull request by fabioz**

### CODE REVIEW

**Comment by int19h** [comment]
It looks like the test runs were timing out on Windows. I've increased the timeout, but you'll need to rebase for the run to pick up the changes to `azure-pipelines.yml`.

**Comment by fabioz** [comment]
@int19h @karthiknadig ping (waiting for review of this pull request).

**Review by karthiknadig — APPROVED** [review]

**Comment by karthiknadig** [comment]
@luabud This is another thing that we can enable with experiments.

**Comment by karthiknadig** [comment]
I think this should be disabled by default and turned on via experiment flag.

What do you think @int19h @luabud ?

**Review by int19h — APPROVED** [review]

**Pull request merged**
