### PR TITLE
Fix #1074: Use "startDebugging" request for subprocesses

### LINKED ISSUE #1074: Use "startDebugging" request for subprocesses
See:
https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_73.md#new-startdebugging-reverse-request

### PR DESCRIPTION
**Pull request by int19h**
Use the request if client advertises the "supportsStartDebuggingRequest" capability.

### CODE REVIEW

**Comment by int19h** [comment]
For "attach" + "connect", the expectation is that the client will interpret it to directly connect to the adapter that is already listening on the specified port - for multiproc, it'll be the same adapter for all sessions (although that is considered an implementation detail from client perspective).

**Comment by mfussenegger** [comment]
> For "attach" + "connect", the expectation is that the client will interpret it to directly connect to the adapter that is already listening on the specified port

If I try that I manage to establish the connection and send `initialize` and also receive a response to that, but then when I send the `attach` request the server closes the connection and the process of the root session terminates.

Is there a way to get more logs? I can't use the `--log-to` option with `python -m debug.py.adapter`.

**Comment by int19h** [comment]
Set the `DEBUGPY_LOG_DIR` environment variable to where you want the logs; it works for all the debugpy subprocesses.

**Comment by mfussenegger** [comment]
Thanks a lot. That helped - turns out I forgot to include the `success` payload in the `startDebugging` response and that caused an error.

Sorry for the noise.

**Pull request merged**
