### PR TITLE
Allow python 3.12 in attach code

### PR DESCRIPTION
**Pull request by AdamYoblick**
Creating this PR so the dll's get generated through github actions. Once they are available as artifacts, I will download them and test locally.

### CODE REVIEW

**Review by rchiodo — APPROVED** [review]

**Comment by AdamYoblick** [comment]
Downloading windows artifacts from https://github.com/microsoft/debugpy/actions/runs/8993404815?pr=1580 and testing attach scenario locally.

**Comment by AdamYoblick** [comment]
The attach DOES work now, we got past the "unknown python version" errors. But breakpoints are not getting hit like they were in when using python 3.11. 

@int19h - I know debugpy works with python 3.12, but is there anything special I need to do to the attach code for breakpoints to be hit when attaching? This scenario works for 3.11 but not 3.12. Thanks!

**Comment by int19h** [comment]
The other place that needs to be updated is here. Without this DLL, it will not be able to set tracing on existing threads.

https://github.com/microsoft/debugpy/blob/09b5af0bb730e2707ec3bbc14c509523eca116c0/src/debugpy/_vendored/pydevd/pydevd_tracing.py#L252-L256

**Comment by int19h** [comment]
But then the DLL itself needs to implement this function for Python 3.12:

https://github.com/microsoft/debugpy/blob/09b5af0bb730e2707ec3bbc14c509523eca116c0/src/debugpy/_vendored/pydevd/pydevd_attach_to_process/common/py_custom_pyeval_settrace.hpp#L170-L190

https://github.com/microsoft/debugpy/blob/09b5af0bb730e2707ec3bbc14c509523eca116c0/src/debugpy/_vendored/pydevd/pydevd_attach_to_process/common/py_custom_pyeval_settrace.hpp#L170-L190

**Comment by int19h** [comment]
That is the trickiest part. This is the implementation for Python 3.11, and I believe much of this has changed for 3.12 (e.g. `use_tracing` doesn't even exist anymore):

https://github.com/microsoft/debugpy/blob/09b5af0bb730e2707ec3bbc14c509523eca116c0/src/debugpy/_vendored/pydevd/pydevd_attach_to_process/common/py_custom_pyeval_settrace_311.hpp

**Comment by sylvainmouquet** [comment]
we can also add python 3.13?

**Pull request closed without merging**
