### PR TITLE
Remove the EPL from the list of licenses

### PR DESCRIPTION
**Pull request by brettcannon**
https://github.com/microsoft/debugpy/blob/main/LICENSE only lists MIT.

### CODE REVIEW

**Comment by brettcannon** [comment]
Or is EPL listed because of debugpy (which is dual-licensed under Apache which is more permissive if you can list that as the other license)?

**Comment by AdamYoblick** [comment]
> Or is EPL listed because of debugpy (which is dual-licensed under Apache which is more permissive if you can list that as the other license)?

I'm actually not sure. @gramster or @karthiknadig would know better. I don't want to tell you the wrong thing 😄

**Comment by gramster** [comment]
This is a throwback to when pydevd was EPL only. Fabio added Apache 2.0 license so we can remove EPL, but I'm not sure if that means we need to add Apache 2.0.

**Comment by AdamYoblick** [comment]
Who do I contact to find out if we have to add apache? CELA?

**Comment by karthiknadig** [comment]
I have sent Adam the details on who to talk to and where to discuss this offline.

**Review by AdamYoblick — APPROVED** [review]

**Pull request merged**
