### PR TITLE
Use importlib instead of imp in qt_loaders.py

### LINKED ISSUE #1531: qt_loaders.py uses the removed imp module (Python 3.12)
## Environment data

- debugpy version: 1.8.1
- OS and version: Windows 10 Enterprise 10.0.19045
- Python version  (& distribution if applicable, e.g. Anaconda): 3.12.1 and pip 24.0
- Using VS Code or Visual Studio: VS Code

## Actual behavior

Pydevd runs into an exception when enabling matplotlib interactive mode for Qt5 backend.

```
Failed to enable GUI event loop integration for 'qt'
Traceback (most recent call last):
  File "c:\Users\Z004N92M\.vscode\extensions\ms-python.python-2024.2.1\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydev_ipython\matplotlibtools.py", line 30, in do_enable_gui    enable_gui(guiname)
  File "c:\Users\Z004N92M\.vscode\extensions\ms-python.python-2024.2.1\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydev_ipython\inputhook.py", line 540, in enable_gui        
    return gui_hook(app)
           ^^^^^^^^^^^^^
  File "c:\Users\Z004N92M\.vscode\extensions\ms-python.python-2024.2.1\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydev_ipython\inputhook.py", line 176, in enable_qt
    from pydev_ipython.qt_for_kernel import QT_API, QT_API_PYQT5
  File "c:\Users\Z004N92M\.vscode\extensions\ms-python.python-2024.2.1\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydev_ipython\qt_for_kernel.py", line 116, in <module>      
    QtCore, QtGui, QtSvg, QT_API = load_qt(api_opts)
                                   ^^^^^^^^^^^^^^^^^
  File "c:\Users\Z004N92M\.vscode\extensions\ms-python.python-2024.2.1\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydev_ipython\qt_loaders.py", line 276, in load_qt
    if not can_import(api):
           ^^^^^^^^^^^^^^^
  File "c:\Users\Z004N92M\.vscode\extensions\ms-python.python-2024.2.1\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydev_ipython\qt_loaders.py", line 152, in can_import       
    if not has_binding(api):
           ^^^^^^^^^^^^^^^^
  File "c:\Users\Z004N92M\.vscode\extensions\ms-python.python-2024.2.1\pythonFiles\lib\python\debugpy\_vendored\pydevd\pydev_ipython\qt_loaders.py", line 115, in has_binding      
    import imp
ModuleNotFoundError: No module named 'imp'
Backend QtAgg is interactive backend. Turning interactive mode on.
```

## Expected  behavior

Interactive mode is turned on without printing a traceback.

## Steps to reproduce:
1. Install `matplotlib 3.8.3`, `PyQt5 5.15.10` and `setuptools  69.1.1`
2. Debug this script with a breakpoint on the print call:
```
import matplotlib
print()
```

### PR DESCRIPTION
**Pull request by stermart**
Resolves #1531.

### CODE REVIEW

**Comment by stermart** [comment]
@microsoft-github-policy-service agree

**Review by bruchim-cisco — APPROVED** [review]

**Comment by stermart** [comment]
@bruchim-cisco my bad, I didn't mean to rerequest a review, I must've misclicked on something. Please disregard.

**Comment by larstokle** [comment]
Hi, Just a gentle reminder. :) It seems this is not merged by some mistake? 
@stermart, @bruchim-cisco

**Comment by stermart** [comment]
Merged new changes, all good on my end @larstokle @bruchim-cisco

**Comment by stermart** [comment]
Should be good now(?) @rchiodo

**Review by rchiodo — APPROVED** [review]

**Pull request merged**
