### PR TITLE
Python 3.10 support (work in progress).

### PR DESCRIPTION
**Pull request by fabioz**
Updated bytecode library (and other minors).

### CODE REVIEW

**Review by int19h — APPROVED** [review]

**Comment by kloczek** [comment]
Looks like there still more to fix:
```
Compiling '/home/tkloczko/rpmbuild/BUILDROOT/python-debugpy-1.4.1-2.fc35.x86_64/usr/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydev_imps/_pydev_sys_patch.py'...
***   File "/usr/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydev_imps/_pydev_SimpleXMLRPCServer.py", line 263
    except Fault, fault:
                ^
SyntaxError: invalid syntax

***   File "/usr/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydev_imps/_pydev_SocketServer.py", line 339
    print '-'*40
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('-'*40)?

Listing '/home/tkloczko/rpmbuild/BUILDROOT/python-debugpy-1.4.1-2.fc35.x86_64/usr/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydev_runfiles'...
***   File "/usr/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydev_imps/_pydev_inspect.py", line 293
    raise TypeError, 'arg is a built-in module'
                   ^
SyntaxError: invalid syntax

Compiling '/home/tkloczko/rpmbuild/BUILDROOT/python-debugpy-1.4.1-2.fc35.x86_64/usr/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydev_runfiles/__init__.py'...
***   File "/usr/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydev_imps/_pydev_pkgutil_old.py", line 543
    except IOError, msg:
                  ^
SyntaxError: invalid syntax

Compiling '/home/tkloczko/rpmbuild/BUILDROOT/python-debugpy-1.4.1-2.fc35.x86_64/usr/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/_debug_adapter/__main__pydevd_gen_debug_adapter_protocol.py'...
***   File "/usr/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydev_imps/_pydev_xmlrpclib.py", line 294
SyntaxError: cannot assign to True

Compiling '/home/tkloczko/rpmbuild/BUILDROOT/python-debugpy-1.4.1-2.fc35.x86_64/usr/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_breakpoints.py'...
***   File "/usr/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevconsole_code_for_ironpython.py", line 105
    except SyntaxError, err:
                      ^
SyntaxError: invalid syntax

Compiling '/home/tkloczko/rpmbuild/BUILDROOT/python-debugpy-1.4.1-2.fc35.x86_64/usr/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_frame.py'...
***   File "/usr/lib/python3.8/site-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_exec.py", line 3
    exec exp in global_vars, local_vars
         ^
SyntaxError: Missing parentheses in call to 'exec'


Compiling '/home/tkloczko/rpmbuild/BUILDROOT/python-debugpy-1.4.1-2.fc35.x86_64/usr/lib/python3.8/site-packages/debugpy/_vendored/pydevd/pydevd_attach_to_process/_test_attach_to_process_linux.py'...
***   File "/usr/lib/python3.8/site-packages/debugpy/_vendored/pydevd/pydevd_attach_to_process/_check.py", line 2
    print add_code_to_python_process.run_python_code(3736, "print(20)", connect_debugger_tracing=False)
          ^
SyntaxError: invalid syntax

```

**Comment by fabioz** [comment]
This is expected and those files will probably not be changed until Python 2 support is dropped.

See: https://github.com/microsoft/debugpy/issues/652 for more info.

**Comment by kloczek** [comment]
It would be really god to have something building cleanly with python +3.8.x.
At ehe moment it is not possible to use last release and even what is in git repo is not ready.

**Comment by fabioz** [comment]
> It would be really god to have something building cleanly with python +3.8.x.
> At ehe moment it is not possible to use last release and even what is in git repo is not ready.

The current main (as well as any release) It does build cleanly (as long as you pass `--no-compile` to `setup.py`).

**Comment by kloczek** [comment]
Issue is that generate python bytecode files is standard part of my package post installation process. So even if that option will be not used still package build fails.

**Comment by int19h** [comment]
@kloczek I would argue that it is an issue in the process, then. Not every .py file in a package should be automatically treated as executable code for a given Python version, and it's perfectly legitimate for the package to conditionally import modules depending on version. Indeed, due to syntactic differences between py2 and py3, it's pretty much unavoidable if one needs to support both. 

From our perspective, the supported build process is `setup.py`. If you use that, and package the result, it should "just work". If you add extra steps after that, then it's up to you to ensure that those steps handle such conditionally executable code correctly.

One thing that we could do, though, is somehow mark the .py files that use py2 syntax - e.g. by some kind of uniform comment - so that any such post-build step could use it to filter them out. Would that help?

**Comment by kloczek** [comment]
> @kloczek I would argue that it is an issue in the process, then. Not every .py file in a package should be automatically treated as executable code for a given Python version, and it's perfectly legitimate for the package to conditionally import modules depending on version. Indeed, due to syntactic differences between py2 and py3, it's pretty much unavoidable if one needs to support both.

I have already packaged almost 600 python modules as rpm and IPS Solaris packages and all those modules have files installed in python site arch/lib directories which is not possible to produce python 3.x bytecode.
Really .. easies way to sort this issue out is branch repo for python 2.x (if support for python 2.x still is needed) and clean all code on master for python 3.x :)

**Comment by int19h** [comment]
It's not necessary to compile to bytecode to install into site-packages, though - indeed, `pip install debugpy` works just fine. I would argue that any packaging system that's not happy with Python code that 1) builds successfully with `setup.py`, and 2) installs successfully with `pip install` (i.e. the two *standard* tools in the Python ecosystem), is doing it wrong.

Maintaining two separate branches for py2 and py3 means more maintenance burden for us - twice as much work for releases, and the need to backport every commit. 

And we're not going to drop support for py2 while we still have a significant number of users who are running on py2, EOL or not (and note that, while the official py2 distro is EOL, there are still companies offering paid support for their own custom builds - e.g. ActiveState). FWIW, personally, I will be ecstatic when we finally do drop it, and I can finally start using Python 3 language features in the product - this would simplify many things! But we're not there yet.

**Comment by kloczek** [comment]
Just tested 1.4.2 an dtill there is a lot of files with python 2.x syntax :(

**Pull request merged**
