### PR TITLE
Flag Python 3.12 support in classifiers

### PR DESCRIPTION
**Pull request by tonybaloney**
Related #1401

### CODE REVIEW

**Review by karthiknadig — APPROVED** [review]

**Comment by int19h** [comment]
Note that we haven't tested this extensively yet beyond the test run itself, so let's merge this after such testing is complete.

**Comment by tonybaloney** [comment]
Do you have a list of test scenarios? I'm running a stack of 3.12 projects, so happy to test some and crowd source the rest

**Comment by int19h** [comment]
Most areas are covered by the tests reasonably well but attach-to-PID is the one that is tricky to test (adversarial code injection into a process is inherently hacky and prone to random failures). Since it's also the area most likely to be affected by changes in CPython internals, that would be my biggest concern for Python 3.12.

**Comment by int19h** [comment]
This has been merged in a separate PR that also updated the build pipeline

**Pull request closed without merging**
